ll/dashboard/run/views.py
# This file is part of Living Labs Challenge, see http://living-labs.net.
#
# Living Labs Challenge is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Living Labs Challenge is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Living Labs Challenge. If not, see <http://www.gnu.org/licenses/>.

from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from .. import core, requires_login

mod = Blueprint('runs', __name__, url_prefix='/runs')


@mod.route('/')
@requires_login
def all():
    systems = core.system.get_systems(g.user['_id'])
    return render_template("run/all.html", user=g.user, systems=systems,
                           config=core.config.config)


@mod.route('/<run_id>')
@requires_login
def run(run_id):
    system = core.system.get_system(g.user['_id'], run_id)
    can_activate, criteria = core.system.activation_status(system['_id'])
    return render_template("run/run.html", system=system, user=g.user,
                           criteria=criteria, can_activate=can_activate,
                           config=core.config.config)


@mod.route('/deactivate/<run_id>')
@requires_login
def deactivate(run_id):
    system = core.system.get_system(g.user['_id'], run_id)
    core.system.set_activation(system['_id'], False)
    flash('Run %s has been deactivated.' % run_id, 'alert-success')
    return redirect(url_for('runs.run', run_id=run_id))


@mod.route('/activate/<run_id>')
@requires_login
def activate(run_id):
    system = core.system.get_system(g.user['_id'], run_id)
    if core.system.activation_status(system['_id'])[0]:
        core.system.set_activation(system['_id'], True)
        flash('Run %s has been activated.' % run_id, 'alert-success')
    else:
        flash('Run %s cannot be activated.' % run_id, 'alert-error')
    return redirect(url_for('runs.run', run_id=run_id))

ll/dashboard/user/views.py
# This file is part of Living Labs Challenge, see http://living-labs.net.
#
# Living Labs Challenge is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Living Labs Challenge is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Living Labs Challenge. If not, see <http://www.gnu.org/licenses/>.

from flask_wtf import FlaskForm as Form
from wtforms import BooleanField
from flask import Blueprint, request, render_template, flash, g, session, \
                    redirect, url_for
from werkzeug import check_password_hash

from .. import core, requires_login
from forms import LoginForm, RegisterForm, ForgotForm
from bson import json_util
import json
mod = Blueprint('user', __name__, url_prefix='/user')


@mod.route('/me/')
@requires_login
def home():
    return render_template("user/profile.html", user=g.user,
                           config=core.config.config)


@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        try:
            user = core.user.get_user_by_email(form.email.data)
        except:
            user = None
        # we use werzeug to validate user's password
        if user and check_password_hash(user["password"], form.password.data):
            # the session can't be modified as it's signed,
            # it's a safe place to store the user id
            session['key'] = user["_id"]
            flash('Logged in as %s' % user["teamname"], 'alert-success')
            return redirect(url_for('home'))
        flash('Wrong email or password', 'alert-warning')
    return render_template("user/login.html", form=form, user=g.user, config=core.config.config)


@mod.route('/logout/', methods=['GET'])
def logout():
    """
    Logout
    """
    g.user = None
    del session['key']
    return redirect("/")


@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        try:
            user = core.user.new_user(form.teamname.data, form.email.data,
                                      password=form.password.data)
        except Exception, e:
            flash(str(e), 'alert-warning')
            return render_template("user/register.html", form=form,
                                   user=g.user, config=core.config.config)
        key = user["_id"]
        session['key'] = key
        flash('Thanks for registering. Your key is: %s' % key, 'alert-success')
        # redirect user to the 'home' method of the user module.
        return redirect(url_for('user.home'))
    return render_template("user/register.html", form=form, user=g.user, config=core.config.config)


@mod.route('/sites/', methods=['GET', 'POST'])
@requires_login
def sites():
    if not g.user["is_participant"]:
        flash('Only participants can select sites. Please register or sign in as a participant', 'alert-warning')
        return redirect(url_for('user.home'))
    if not g.user["is_verified"]:
        flash('You need to be verified first, please send the organizers a signed <a href="%s">registration form<a/>.'
              % core.config.config["URL_REGISTRATION_FORM"], 'alert-warning')
        return redirect(url_for('user.home'))

    class SitesForm(Form):
        pass

    usersites = core.user.get_sites(g.user["_id"])
    for site in core.site.get_sites():
        if "enabled" in site and not site["enabled"]:
            continue
        description = site["terms"] if "terms" in site and site["terms"] else "No additional terms."
        default = True if site['_id'] in usersites else False
        setattr(SitesForm, site['_id'], BooleanField(site['name'] + ("<img src=\"/static/icon_robot.svg\" style=\"height: 14px; position: relative;top: -3px;left: 2px;\"/>"
                                                                     if site["is_robot"] else ""),
                                                     description=description,
                                                     default=default))

    form = SitesForm(request.form)
    if form.validate_on_submit():
        sites = [k for k in form.data if form.data[k]]
        core.user.set_sites(g.user["_id"], sites)
        flash('Agreements to site terms have been saved.', 'alert-success')
        return redirect(url_for('site.home'))
    return render_template("user/sites.html", form=form, user=g.user, config=core.config.config)


@mod.route('/forgot/', methods=['GET', 'POST'])
def forgot():
    form = ForgotForm(request.form)
    if form.validate_on_submit():
        try:
            core.user.reset_password(form.email.data)
        except Exception, e:
            flash(str(e), 'alert-warning')
            return redirect(url_for('user.forgot'))
        flash('A new password has been sent to %s.' % form.email.data,
              'alert-success')
        return redirect("/")
    return render_template("user/forgot.html", form=form, user=g.user, config=core.config.config)

ll/dashboard/templates/base.html
{# This file is part of Living Labs Challenge, see http://living-labs.net.
 #
 # Living Labs Challenge is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Lesser General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # Living Labs Challenge is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU Lesser General Public License for more details.
 #
 # You should have received a copy of the GNU Lesser General Public License
 # along with Living Labs Challenge. If not, see <http://www.gnu.org/licenses/>.
 #}
<html>
  <head>
    <title>{% block title %}Living Labs Dashboard{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/main.css" />
    {% endblock %}
    {% block script %}
    <script src="/static/jquery-2.0.3.min.js" type="text/javascript"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    {% endblock %}
  </head>
  <body>
  	<div id="navbar" class="navbar navbar-default navbar-fixed-top">
	    <div class="container">
	      <div class="navbar-header">
	        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
	        <a class="navbar-brand" href="#">
	          {{ config.COMPETITION_NAME  }} Dashboard</a>
	        <span class="navbar-text navbar-version pull-left"><b></b></span>
	      </div>
			<div class="collapse navbar-collapse nav-collapse">
			  <ul class="nav navbar-nav">
			    <li class="divider-vertical"></li>
			        <li><a href="{{ config.URL_WEB }}">Website</a></li>
			        <li><a href="/">Dashboard</a></li>
			        <li><a href="{{ config.URL_DOC }}">Documentation</a></li>
			</div>
	    </div>
	</div>
<div class="container">
<div class="row">
<div class="col-md-9 dmbs-main">
	      <div class="navbar-header">
	        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
	      </div>
	<ul class="nav nav-tabs">
	  <li {% if request.path == "/" %}class="active"{% endif %}><a href="/">Home</a></li>
	  <li {% if request.path.startswith("/participant") %}class="active"{% endif %}><a href="/participant">Participants</a></li>
	  <li {% if request.path.startswith("/site") %}class="active"{% endif %}><a href="/site">Sites</a></li>
	  <li {% if request.path.startswith("/my") %}class="active"{% endif %}><a href="/my">My</a></li>
      <li {% if request.path.startswith("/run") %}class="active"{% endif %}><a href="{{ url_for('runs.all') }}">Runs</a></li>
      {% if user.is_admin %}
	  <li {% if request.path.startswith("/admin") %}class="active"{% endif %}><a href="/admin">Admin</a></li>
      {% endif %}
	  {% if user %}
	  <li class="dropdown {% if request.path.startswith("/user") %}active{% endif %}">
	    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	    <span class="glyphicon glyphicon-user"></span> {{ user.teamname }}<span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu">
	      <li class="{% if request.path.startswith("/user/me") %}active{% endif %}"><a href="/user/me">Profile</a></li>
	      {% if user.is_participant %}
	      <li class="{% if request.path.startswith("/user/sites") %}active{% endif %}"><a href="/user/sites/">Site agreements</a></li>
	      {% endif %}
	      <li class="divider"></li>
	      <li><a href="/user/logout"><span class="glyphicon glyphicon-off"></span> Logout</a></li>
	    </ul>
	  </li>
	  {% else %}
	  <li {% if request.path.startswith("/user/login") %}class="active"{% endif %}>  
	  <a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a>
	  </li>
	  <li {% if request.path.startswith("/user/register") %}class="active"{% endif %}>
	  <a href="{{ url_for('user.register') }}"><span class="glyphicon glyphicon-user"></span> Register</a>
	  </li>
	  {% endif %}
	</ul>
	<div class="page-header">
    	<h1>{% block header %}Home{% endblock %}</h1>
    </div>
    <div id="messages-wrap">
      <div id="messages">
        {% for category, msg in get_flashed_messages(with_categories=true) %}
          <p class="alert {{ category }}">{{ msg|safe  }}</p>
        {% endfor %}
      </div>
    </div>
    <div id="content">
    {% block content %}    
	{% if not verified and user.is_participant %}
	<div class="alert alert-warning">
    Your account has not yet been verified. Please send the 
    <a href="{{config.URL_REGISTRATION_FORM}}">agreement form</a> to the organizers.
    If you already did that and if verification takes longer than a few hours, please do not 
    hesitate to <a href="{{config.EMAIL_FROM}}">send the organizers a quick email</a>.
    </div>
	{% else %}
	{% if not sites and user.is_participant %}
	<div class="alert alert-warning">
    You have not yet signed up for any sites. You will need to individually
    <a href="{{ url_for('user.sites') }}">sign up</a> for each site to obtain 
    their data.
    </div>
	{% endif %}	
	{% endif %}
    <p>Welcome to the dashboard of Living Labs for {{config.COMPETITION_NAME }}. This dashboard can be used to register
    to the lab and to view live stats on your performance.</p>
    <blockquote><p>Give us your ranking, we’ll have it clicked!</p></blockquote>
    {% endblock %}
    </div>
 </div>
 </div>
 </div>
 <footer class="footer">
  <div class="container">
    <p class="text-muted">
        &copy; Copyright 2016, Living Labs.<br/>
    </p>
  </div>
</footer>
  </body>
</html>