ll/dashboard/run/views.py
# This file is part of Living Labs Challenge, see http://living-labs.net.
#
# Living Labs Challenge is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Living Labs Challenge is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Living Labs Challenge. If not, see <http://www.gnu.org/licenses/>.

from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from .. import core, requires_login

mod = Blueprint('runs', __name__, url_prefix='/runs')


@mod.route('/')
@requires_login
def all():
    systems = core.system.get_systems(g.user['_id'])
    return render_template("run/all.html", user=g.user, systems=systems,
                           config=core.config.config)


@mod.route('/<run_id>')
@requires_login
def run(run_id):
    system = core.system.get_system(g.user['_id'], run_id)
    can_activate, criteria = core.system.activation_status(system['_id'])
    return render_template("run/run.html", system=system, user=g.user,
                           criteria=criteria, can_activate=can_activate,
                           config=core.config.config)


@mod.route('/deactivate/<run_id>')
@requires_login
def deactivate(run_id):
    system = core.system.get_system(g.user['_id'], run_id)
    core.system.set_activation(system['_id'], False)
    flash('Run %s has been deactivated.' % run_id, 'alert-success')
    return redirect(url_for('runs.run', run_id=run_id))


@mod.route('/activate/<run_id>')
@requires_login
def activate(run_id):
    system = core.system.get_system(g.user['_id'], run_id)
    if core.system.activation_status(system['_id'])[0]:
        core.system.set_activation(system['_id'], True)
        flash('Run %s has been activated.' % run_id, 'alert-success')
    else:
        flash('Run %s cannot be activated.' % run_id, 'alert-error')
    return redirect(url_for('runs.run', run_id=run_id))

ll/dashboard/templates/run/all.html
{# This file is part of Living Labs Challenge, see http://living-labs.net.
 #
 # Living Labs Challenge is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Lesser General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # Living Labs Challenge is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU Lesser General Public License for more details.
 #
 # You should have received a copy of the GNU Lesser General Public License
 # along with Living Labs Challenge. If not, see <http://www.gnu.org/licenses/>.
 #}
{% extends "base.html" %}
{% block header %}
My Runs
{% endblock %}
{% block content %}
    <p>These are the runs you have submitted. You need to activate your runs before
    they will be displayed on the site. A run can only be activated if it is
    complete. This means that you need to have submitted a ranking for every
    query of the site. You can submit your rankings for the queries via the
    API.</p>
    <table class="table table-striped table-hover ">
    <thead>
    <tr>
        <th>Run ID</th>
        <th>Site ID</th>
        <th>Active</th>
    </tr>
    </thead>
    <tbody>
    {%  for system in systems %}
        <tr>
            <td><a href="{{ url_for('runs.run', run_id=system['runid']) }}">{{ system['runid'] }}</a></td>
            <td>{{ system['siteid'] }}</td>
            <td>{{ system['active'] }}</td>
        </tr>
    {%  endfor %}
  	</tbody>
	</table>
{% endblock %}

ll/dashboard/templates/run/run.html
{# This file is part of Living Labs Challenge, see http://living-labs.net.
 #
 # Living Labs Challenge is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Lesser General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # Living Labs Challenge is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU Lesser General Public License for more details.
 #
 # You should have received a copy of the GNU Lesser General Public License
 # along with Living Labs Challenge. If not, see <http://www.gnu.org/licenses/>.
 #}
{% extends "base.html" %}
{% block header %}
Run {{ system['runid'] }}
{% endblock %}
{% block content %}
    <table class="table table-striped table-hover ">
    <tbody>
    <tr>
        <td>Run ID:</td>
        <td>{{ system['runid'] }}</td>
    </tr>
    <tr>
        <td>Site ID:</td>
        <td>{{ system['siteid'] }}</td>
    </tr>
    <tr>
        <td>Active:</td>
        <td>{{ system['active'] }}</td>
    </tr>
    <tr>
        <td>Impressions:</td>
        <td><strong>{{ system['nr_times_displayed'] }}</strong></td>
    </tr>
    </tbody>
	</table>
    {% if not can_activate and not system['active'] %}
        <div class="alert alert-warning">
            <strong>You cannot activate this run yet.</strong><br />
            {{ criteria }}
        </div>
    {% endif %}
    {% if can_activate and not system['active'] %}
        <div class="form-group">
            <div class="alert alert-info">
                You can use the button below to <strong>activate</strong> this run
            </div>
      		<div>
        		<a href="{{ url_for('runs.activate', run_id=system['runid']) }}" class="btn btn-primary">Activate</a>
      		</div>
    	</div>
    {% endif %}
    {% if system['active'] %}
        <div class="form-group">
            <div class="alert alert-info">
                <strong>This run is currently active and is being displayed on the site.</strong><br/>
                You can use the button below to deactivate this run and prevent it from being used.
            </div>
      		<div>
                <a href="{{ url_for('runs.deactivate', run_id=system['runid']) }}" class="btn btn-primary">Deactivate</a>
      		</div>
    	</div>
    {% endif %}
{% endblock %}